// TODO: usar estrategia que corresponda segun parametro de entrada

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Imprimir configuraciones
        run: |
          echo "type: ${{ github.event.inputs.type }}"