// TODO: usar estrategia que corresponda segun parametro de entrada

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      type:
        description: 'Project type [node, react, flutter]'
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Imprimir configuraciones
        run: |
          echo "type: ${{ github.event.inputs.type }}"