// TODO: usar estrategia que corresponda segun parametro de entrada

inputs:
  type:
    description: 'Project type [node, react, flutter]'
    required: true

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Imprimir configuraciones
        run: |
          echo "type: ${{ inputs.type }}"