inputs:
  type:
    description: 'Set always-auth in npmrc.'
    default: 'false'
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Imprimir configuraciones
        run: |
          echo "type: ${{ steps }}"