name: Node.js projects CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - name: Checkout Code
        uses: ../common/checkout.yml
      - name: Checkout Code
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - name: Quality
        uses: ../common/sonar.yml
      - name: Security
        uses: ../common/security.yml
